allowBuilds:
    "@parcel/watcher": false
    "@swc/core": false
    sharp: false
    unrs-resolver: false

minimumReleaseAgeExclude:
    - "@next/swc-linux-x64-musl@16.3.6"
    - eslint-config-next@16.3.6
    - next@16.3.6
